#!/usr/bin/env python3
"""Generate src/lib/strategyData.generated.json from the Python strategy engine.

The React dashboard (src/lib/strategyAdvisor.ts) does NOT reimplement basic
strategy or Illustrious 18 / Fab Four logic. Instead it looks up decisions in
the JSON file this script produces, which is generated by exhaustively
querying the real, tested `BasicStrategy` / `HiLoDeviationStrategy` classes.

Run this after changing anything in blackjack/strategy/, then commit the
regenerated JSON alongside your change:

    python3 scripts/generate_strategy_data.py

`tests/test_strategy_data_sync.py` fails CI if the committed JSON is stale.
"""

from __future__ import annotations

import itertools
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from blackjack.core.actions import Action
from blackjack.core.card import Card, Rank
from blackjack.core.hand import Hand
from blackjack.core.rules import BlackjackRules
from blackjack.strategy.basic_strategy import BasicStrategy
from blackjack.strategy.deviations import DEVIATIONS

OUTPUT_PATH = Path(__file__).resolve().parent.parent / "src" / "lib" / "strategyData.generated.json"

DEALER_UPCARDS = list(range(2, 12))  # 2..10, 11 = Ace
HARD_VALUES = list(range(4, 21))
SOFT_VALUES = list(range(12, 21))  # A,A (12) .. A,9 (20) -- covers an Ace pair once split is unavailable

# (rank used to build the pair, display key, blackjack_value of one card)
PAIR_RANKS = [
    (Rank.TWO, "2"),
    (Rank.THREE, "3"),
    (Rank.FOUR, "4"),
    (Rank.FIVE, "5"),
    (Rank.SIX, "6"),
    (Rank.SEVEN, "7"),
    (Rank.EIGHT, "8"),
    (Rank.NINE, "9"),
    (Rank.TEN, "10"),
    (Rank.ACE, "A"),
]

RULE_AXES = list(itertools.product([False, True], [False, True], [False, True]))
# axis order: dealer_hits_soft_17, double_after_split, late_surrender


def rules_key(h17: bool, das: bool, ls: bool) -> str:
    return f"{'h17' if h17 else 's17'}_{'das' if das else 'nodas'}_{'ls' if ls else 'nols'}"


def build_rules(h17: bool, das: bool, ls: bool) -> BlackjackRules:
    return BlackjackRules(
        dealer_hits_soft_17=h17,
        double_after_split=das,
        late_surrender=ls,
        double_allowed=True,
        insurance_allowed=True,
    )


def dealer_card(up_val: int) -> Card:
    rank = Rank.ACE if up_val == 11 else Rank.from_str(str(up_val))
    return Card(rank=rank)


def make_hard_hand(value: int) -> Hand:
    """Build a 2-card, non-ace hand summing to `value` (4..20)."""
    if value <= 12:
        first, second = 2, value - 2
    else:
        first, second = 10, value - 10
    return Hand(cards=[Card(rank=Rank.from_str(str(first))), Card(rank=Rank.from_str(str(second)))])


def make_soft_hand(value: int) -> Hand:
    """Build an A + X hand where value = 11 + X (12..20). value=12 is A,A."""
    if value == 12:
        return Hand(cards=[Card(rank=Rank.ACE), Card(rank=Rank.ACE)])
    other = value - 11
    return Hand(cards=[Card(rank=Rank.ACE), Card(rank=Rank.from_str(str(other)))])


def make_pair_hand(rank: Rank) -> Hand:
    return Hand(cards=[Card(rank=rank), Card(rank=rank)])


def action_str(a: Action) -> str:
    return a.value


def generate() -> dict:
    strategy = BasicStrategy()
    hard_table: dict[str, dict] = {}
    soft_table: dict[str, dict] = {}
    pair_table: dict[str, dict] = {}

    initial_hard_actions = [Action.HIT, Action.STAND, Action.DOUBLE, Action.SURRENDER]
    no_surrender_actions = [Action.HIT, Action.STAND, Action.DOUBLE]
    hit_only_actions = [Action.HIT, Action.STAND]
    initial_pair_actions = [Action.HIT, Action.STAND, Action.DOUBLE, Action.SPLIT, Action.SURRENDER]

    for h17, das, ls in RULE_AXES:
        key = rules_key(h17, das, ls)
        rules = build_rules(h17, das, ls)
        hard_table[key] = {}
        soft_table[key] = {}
        pair_table[key] = {}

        for value in HARD_VALUES:
            hard_table[key][str(value)] = {}
            for up in DEALER_UPCARDS:
                dealer = dealer_card(up)
                hard_table[key][str(value)][str(up)] = {
                    "initial": action_str(strategy.decide(make_hard_hand(value), dealer, initial_hard_actions, rules)),
                    "noSurrender": action_str(strategy.decide(make_hard_hand(value), dealer, no_surrender_actions, rules)),
                    "hitOnly": action_str(strategy.decide(make_hard_hand(value), dealer, hit_only_actions, rules)),
                }

        for value in SOFT_VALUES:
            soft_table[key][str(value)] = {}
            for up in DEALER_UPCARDS:
                dealer = dealer_card(up)
                soft_table[key][str(value)][str(up)] = {
                    "initial": action_str(strategy.decide(make_soft_hand(value), dealer, initial_hard_actions, rules)),
                    "noSurrender": action_str(strategy.decide(make_soft_hand(value), dealer, no_surrender_actions, rules)),
                    "hitOnly": action_str(strategy.decide(make_soft_hand(value), dealer, hit_only_actions, rules)),
                }

        for rank, rank_key in PAIR_RANKS:
            pair_table[key][rank_key] = {}
            for up in DEALER_UPCARDS:
                dealer = dealer_card(up)
                decision = strategy.decide(make_pair_hand(rank), dealer, initial_pair_actions, rules)
                pair_table[key][rank_key][str(up)] = action_str(decision)

    deviations = [dev.to_dict() for dev in DEVIATIONS]

    return {
        "$comment": (
            "AUTO-GENERATED by scripts/generate_strategy_data.py from blackjack/strategy/. "
            "Do not hand-edit; regenerate instead."
        ),
        "dealerUpcards": DEALER_UPCARDS,
        "hard": hard_table,
        "soft": soft_table,
        "pairs": pair_table,
        "deviations": deviations,
        "insurance": {"action": "TAKE", "trueCountThreshold": 3.0},
    }


def main() -> None:
    data = generate()
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(json.dumps(data, indent=2, sort_keys=False) + "\n", encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH} ({OUTPUT_PATH.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
